### ISSUE TITLE
Rule lingui/no-unlocalized-strings: TypeError: Cannot destructure property 'esTreeNodeToTSNodeMap' of 'parserServices' as it is undefined.

### ISSUE THREAD

**Issue by Jack-Works** [lingui/eslint-plugin#46]
This error only happens for `lingui/no-unlocalized-strings`, other rules are fine.

- eslint@9.8.0
- eslint-plugin-lingui@0.3.0
- typescript-eslint@8.0.0

```
TypeError: Error while loading rule 'lingui/no-unlocalized-strings': Cannot destructure property 'esTreeNodeToTSNodeMap' of 'parserServices' as it is undefined.
Occurred while linting ...
    at Object.create (eslint-plugin-lingui/lib/rules/no-unlocalized-strings.js:136:17)
    at createRuleListeners (eslint/lib/linter/linter.js:977:21)
    at eslint/lib/linter/linter.js:1108:84
    at Array.forEach (<anonymous>)
    at runRules (eslint/lib/linter/linter.js:1039:34)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (eslint/lib/linter/linter.js:1947:31)
    at Linter._verifyWithFlatConfigArray (eslint/lib/linter/linter.js:2086:21)
    at Linter.verify (eslint/lib/linter/linter.js:1547:61)
    at Linter.verifyAndFix (eslint/lib/linter/linter.js:2323:29)
    at verifyText (eslint/lib/eslint/eslint.js:498:48)
```

**Comment by itsarijitray** [comment]
@Jack-Works @andrii-bodnar Can I give it a shot?

**Comment by andrii-bodnar** [comment]
@itsarijitray sure, thank you!

**Comment by Arthur944** [comment]
Are there any updates here? This rule would be the most useful one

**Comment by Arthur944** [comment]
This seems to solve it, around line 71 in no-unlocalized-strings.ts. Not sure how to open a pull request though

```
    const {
      options: [option],
    } = context
    const parserServices = context.parserServices || context.sourceCode.parserServices
```

**Comment by andrii-bodnar** [comment]
@Arthur944 thank you, we'd be happy to accept the PR. Please see the [Creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) article for more information on that.
